/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Batter {
	/**
	 * Batter's name
	 */
	name: string;
	/**
	 * Runs in each category made by player, 1st index is normal runs, 2nd is 4's, 3rd is 6's. Default is -1 to display it as a '-'
	 */
	runs: any[];
	/**
	 * Number of balls the batter has faced, -1 to display as '-'
	 */
	balls: number;
	/**
	 * If populated the player will be shown as out
	 */
	dismissal: string;
}
