/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Batter {
	/**
	 * Batter's name
	 */
	name: string;
	/**
	 * Runs in each category made by player, 1st index is total runs, 2nd is 4's, 3rd is 6's
	 */
	runs: any[];
	/**
	 * Number of balls the batter has faced
	 */
	balls: number;
	/**
	 * If populated the player will be shown as out
	 */
	dismissal: string;
	/**
	 * If true the batter is currently on the pitch, false if the batter has yet to bat or has gone out
	 */
	batting: boolean;
	/**
	 * If true the batter is facing the bowler, false if the batter is running
	 */
	facing: boolean;
}
