/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentInnings {
	/**
	 * Current runs scored
	 */
	runs: number;
	/**
	 * Current wickets
	 */
	wickets: number;
	/**
	 * Current over with decimal, e.g. 15.2
	 */
	over: number;
	/**
	 * The team that is bowling this innings
	 */
	bowlingTeam: string;
	/**
	 * The team that is batting this innings
	 */
	battingTeam: string;
	/**
	 * Three letter abreviations for playing teams. [Bowlers, Batters]
	 */
	TLAs: string[];
	currentBowler: {
		/**
		 * Bowler's name
		 */
		name: string;
		/**
		 * Number of overs bowled with decimal, e.g. 15.2
		 */
		overs: number;
		/**
		 * Number of overs where the batsman has not made a run
		 */
		maidenOvers: number;
		/**
		 * Number of runs made off the bowler
		 */
		runs: number;
		/**
		 * The amount of wickets a bowler has made
		 */
		wickets: number;
		/**
		 * Wides and No Balls, [wide, noball]
		 */
		badBalls: any[];
	};
	currentBatterFacing: {
		/**
		 * Batter's name
		 */
		name: string;
		/**
		 * Runs in each category made by player, 1st index is normal runs, 2nd is 4's, 3rd is 6's. Default is -1 to display it as a '-'
		 */
		runs: any[];
		/**
		 * Number of balls the batter has faced, -1 to display as '-'
		 */
		balls: number;
		/**
		 * If populated the player will be shown as out
		 */
		dismissal: string;
	};
	currentBatterRunning: {
		/**
		 * Batter's name
		 */
		name: string;
		/**
		 * Runs in each category made by player, 1st index is normal runs, 2nd is 4's, 3rd is 6's. Default is -1 to display it as a '-'
		 */
		runs: any[];
		/**
		 * Number of balls the batter has faced, -1 to display as '-'
		 */
		balls: number;
		/**
		 * If populated the player will be shown as out
		 */
		dismissal: string;
	};
	bowlers: {
		/**
		 * Bowler's name
		 */
		name: string;
		/**
		 * Number of overs bowled with decimal, e.g. 15.2
		 */
		overs: number;
		/**
		 * Number of overs where the batsman has not made a run
		 */
		maidenOvers: number;
		/**
		 * Number of runs made off the bowler
		 */
		runs: number;
		/**
		 * The amount of wickets a bowler has made
		 */
		wickets: number;
		/**
		 * Wides and No Balls, [wide, noball]
		 */
		badBalls: any[];
	}[];
	batters: {
		/**
		 * Batter's name
		 */
		name: string;
		/**
		 * Runs in each category made by player, 1st index is normal runs, 2nd is 4's, 3rd is 6's. Default is -1 to display it as a '-'
		 */
		runs: any[];
		/**
		 * Number of balls the batter has faced, -1 to display as '-'
		 */
		balls: number;
		/**
		 * If populated the player will be shown as out
		 */
		dismissal: string;
	}[];
}
