/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentInnings {
	/**
	 * Current runs scored
	 */
	runs?: number;
	/**
	 * Current wickets
	 */
	wickets?: number;
	/**
	 * Current over with decimal, e.g. 15.2
	 */
	over?: number;
	/**
	 * The team that is bowling this innings
	 */
	bowlingTeam?: string;
	/**
	 * The team that is batting this innings
	 */
	battingTeam?: string;
	/**
	 * Three letter abreviations for playing teams. [Bowlers, Batters]
	 */
	TLAs?: string[];
	[k: string]: any;
}
