/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentInnings {
	/**
	 * Current runs scored
	 */
	runs: number;
	/**
	 * Current extra runs
	 */
	extras: number;
	/**
	 * Current wickets
	 */
	wickets: number;
	/**
	 * Array of all overs, length is the overs past, the last index is the current over
	 */
	overs: {
		/**
		 * The balls in the past over, any as strings may be included, e.g. [0, 4, Wide, NB, 3, W]
		 */
		over: (number | string)[];
		/**
		 * Number of balls left in the over
		 */
		ballsLeft: number;
		/**
		 * Name of bowler
		 */
		bowler: string;
	}[];
	/**
	 * The team that is bowling this innings
	 */
	bowlingTeam: string;
	/**
	 * The team that is batting this innings
	 */
	battingTeam: string;
	/**
	 * Three letter abreviations for playing teams. [Bowlers, Batters]
	 */
	TLAs: string[];
	bowlers: {
		/**
		 * Bowler's name
		 */
		name: string;
		/**
		 * Number of overs bowled with decimal, e.g. 15.2
		 */
		overs: string;
		/**
		 * Number of overs where the batsman has not made a run
		 */
		maidenOvers: number;
		/**
		 * Number of runs made off the bowler
		 */
		runs: number;
		/**
		 * The amount of wickets a bowler has made
		 */
		wickets: number;
		/**
		 * Wides and No Balls, [wide, noball]
		 */
		badBalls: any[];
		/**
		 * True if the bowler is currently bowling, false if they are not
		 */
		bowling: boolean;
	}[];
	batsmen: {
		/**
		 * Batter's name
		 */
		name: string;
		/**
		 * Total run made
		 */
		runs: number;
		/**
		 * Number of fours made
		 */
		fours: number;
		/**
		 * Number of sixes made
		 */
		sixes: number;
		/**
		 * Number of balls the batter has faced
		 */
		balls: number;
		/**
		 * If populated the player will be shown as out
		 */
		dismissal: string;
		/**
		 * State of batter
		 */
		batting: 'WAITING' | 'BATTING' | 'OUT';
		/**
		 * If true the batter is facing the bowler, false if the batter is running
		 */
		facing: boolean;
	}[];
}
