/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Teams = {
	/**
	 * The name of the team
	 */
	name?: string;
	/**
	 * Three-letter abbreviation of team name. e.g. India => IND
	 */
	tla?: string;
	/**
	 * Total runs the team has currently made
	 */
	totalRuns?: number;
	/**
	 * Total amount of runners out
	 */
	wickets?: number;
	/**
	 * Is the team batting or fielding
	 */
	currentPosition?: 'batting' | 'fielding';
	players?: {
		[k: string]: any;
	}[];
}[];
